### ISSUE TITLE
macos 10.12 build and load issue

### ISSUE THREAD

**Issue by fr0zenrain** [libtorrent/libtorrent#13]
in macos 10.12 build all ok,but load failed, i also tried gcc  and it load failed too,but the missing symbol is different,my boost version is 1.59.some one met this issue?

>>> import libtorrent
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/libtorrent.so, 2): Symbol not found: __ZN5boost6python6detail13current_scopeE
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/libtorrent.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/libtorrent.so

**Comment by arvidn** [comment]
you should try github.com/arvidn/libtorrent

**Comment by fr0zenrain** [comment]
thank you, same error,it's sad! finally give up, i will try others library.
