### ISSUE TITLE
MSVS 2013 sp4 linking error.

### ISSUE THREAD

**Issue by filonenko-mikhail** [libtorrent/libtorrent#6]
It seems that MSVC 2013 sp4 dislikes non-virtual inline destructors with error 'symbol already defined' for all object files which contains 'include 'libtorrent/file_storage.hpp'

https://github.com/libtorrent/libtorrent/blob/master/include/libtorrent/file_storage.hpp#L87

**Comment by arvidn** [comment]
I see. that destructor should probably be moved to the .cpp file anyway.

**Comment by arvidn** [comment]
actually. this change has been made already. take a look at the latest version:
https://github.com/arvidn/libtorrent
This repository is a stale mirror

**Comment by filonenko-mikhail** [comment]
Thanks. So, next time I will go to original repository.
